GET localhost:5000/api/user/doctors
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJjZGRlMTIyNS0xN2Q4LTUxOGUtYmExYy1lYTVmN2FmNTIyODEiLCJpYXQiOjE1ODcxMjMzNTksImV4cCI6MTU4Nzk4NzM1OX0.huqO0df81pYnRQoVeKDnjZJO9giiEUGJkLh_08hSMywvFLE5zT8TpeJBR7gcHc7oGmIbdwV2qne5Nl5pcLcH3A

###

POST localhost:5000/api/user/available
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJjZGRlMTIyNS0xN2Q4LTUxOGUtYmExYy1lYTVmN2FmNTIyODEiLCJpYXQiOjE1ODcxMjMzNTksImV4cCI6MTU4Nzk4NzM1OX0.huqO0df81pYnRQoVeKDnjZJO9giiEUGJkLh_08hSMywvFLE5zT8TpeJBR7gcHc7oGmIbdwV2qne5Nl5pcLcH3A

###
