GET localhost:5000/api/user/doctors
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJjZGRlMTIyNS0xN2Q4LTUxOGUtYmExYy1lYTVmN2FmNTIyODEiLCJpYXQiOjE1ODc2MzcyNjgsImV4cCI6MTU4ODUwMTI2OH0.P3n67f637krSX2JxiwCAprMnnED-xPh_DJqmZ6_kC94Z1PrpeOoQSgc2UD6uC2VbSXNns0bgkU2GlqpPVfLMZQ
###

POST localhost:5000/api/user/available
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJjZGRlMTIyNS0xN2Q4LTUxOGUtYmExYy1lYTVmN2FmNTIyODEiLCJpYXQiOjE1ODc2MzcyNjgsImV4cCI6MTU4ODUwMTI2OH0.P3n67f637krSX2JxiwCAprMnnED-xPh_DJqmZ6_kC94Z1PrpeOoQSgc2UD6uC2VbSXNns0bgkU2GlqpPVfLMZQ
###
