CREATE TABLE chat_message
(
	id VARCHAR(200) NOT NULL,
	room VARCHAR(200) NOT NULL,
	type VARCHAR(200) NOT NULL,
	source VARCHAR(200) NOT NULL,
	body LONGTEXT NOT NULL,
	author BIGINT(20) NOT NULL,
	created DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
	updated DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CONSTRAINT chat_message_pk
		PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
