CREATE TABLE chat_room (
	id VARCHAR(200) NOT NULL,
	participant_first BIGINT(20) NOT NULL,
	participant_second BIGINT(20) NULL,
	message_count BIGINT(20) DEFAULT 0 NOT NULL,
	created DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
	updated DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CONSTRAINT chat_room_pk
		PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
