GET localhost:5000/api/chat/room
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNTg2ODQ3MDEzLCJleHAiOjE1ODc3MTEwMTN9.uaybx86JdAryJrmWhsOlxnsTHPwf2dG6CHH6zMaj7SLZF5Fd2szfVwumxn8key7RRXhEKTHuSKmGsWQxk0PHyw

###

POST localhost:5000/api/chat/room
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNTg2ODQ3MDEzLCJleHAiOjE1ODc3MTEwMTN9.uaybx86JdAryJrmWhsOlxnsTHPwf2dG6CHH6zMaj7SLZF5Fd2szfVwumxn8key7RRXhEKTHuSKmGsWQxk0PHyw

[
  2
]

###

POST localhost:5000/api/chat/message
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNTg2ODQ3MDEzLCJleHAiOjE1ODc3MTEwMTN9.uaybx86JdAryJrmWhsOlxnsTHPwf2dG6CHH6zMaj7SLZF5Fd2szfVwumxn8key7RRXhEKTHuSKmGsWQxk0PHyw

{
  "room": "221be42e-5c97-4fc8-b0df-c4f276f44a7e",
  "type": "TEXT",
  "source": "USER",
  "author": 3,
  "body": "fourth message"
}

###

GET localhost:5000/api/chat/room/221be42e-5c97-4fc8-b0df-c4f276f44a7e
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNTg2ODQ3MDEzLCJleHAiOjE1ODc3MTEwMTN9.uaybx86JdAryJrmWhsOlxnsTHPwf2dG6CHH6zMaj7SLZF5Fd2szfVwumxn8key7RRXhEKTHuSKmGsWQxk0PHyw

###

GET localhost:5000/api/chat/poll
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNTg2ODQ3MDEzLCJleHAiOjE1ODc3MTEwMTN9.uaybx86JdAryJrmWhsOlxnsTHPwf2dG6CHH6zMaj7SLZF5Fd2szfVwumxn8key7RRXhEKTHuSKmGsWQxk0PHyw

###

POST localhost:5000/api/chat/room/221be42e-5c97-4fc8-b0df-c4f276f44a7e
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNTg2ODQ3MDEzLCJleHAiOjE1ODc3MTEwMTN9.uaybx86JdAryJrmWhsOlxnsTHPwf2dG6CHH6zMaj7SLZF5Fd2szfVwumxn8key7RRXhEKTHuSKmGsWQxk0PHyw

###

